### ISSUE TITLE
About Running Environment

### ISSUE THREAD

**Issue by mchenryXD** [jamjamjon/usls#19]
Hello author  
What specific operating environment is needed  pytorch or libtorch？

**Comment by mchenryXD** [comment]
![1](https://github.com/jamjamjon/usls/assets/77257565/5b10cb14-ec48-40b2-8f1a-e673be0f5c11)
I am trying to start yolov8-falldown

**Comment by jamjamjon** [comment]
On my local computer, which runs Ubuntu, I didn't encounter this issue. I'll find a Windows machine to test and see what the cause might be.

**Comment by jamjamjon** [comment]
> Hello author  
> 
> What specific operating environment is needed  pytorch or libtorch？

Only `ort`. By the way, what is the rustc version?

**Comment by mchenryXD** [comment]
The problem has been resolved 
The reason is that the ONNX file was interrupted during the download process

**Comment by mchenryXD** [comment]
But there are still some issues 
How should I obtain the name of the saved rendering image and How should I obtain the model execution results if I don't need to render the image

**Comment by jamjamjon** [comment]
> But there are still some issues How should I obtain the name of the saved rendering image and How should I obtain the model execution results if I don't need to render the image

You can find some api here:  `src/ys/y.rs`

For example: get detection results
```
let ys = model.run(&xs)?;
// ys.bboxes()
```

**Comment by mchenryXD** [comment]
> > 但还存在一些问题，如何获取保存的渲染图片的名称？如果不需要渲染图片，如何获取模型执行结果？
> 
> 你可以在这里找到一些 API： `src/ys/y.rs`
> 
> 例如：获取检测结果
> 
> ```
> let ys = model.run(&xs)?;
> // ys.bboxes()
> ```

thinks

**Comment by mchenryXD** [comment]
> > 还存在一些问题，如何获取渲染的图像？如果不需要渲染图像，如何获取模型结果？
> 
> 或者找到一些 API： `src/ys/y.rs`
> 
> 例如：捕获检测结果
> 
> ```
> let ys = model.run(&xs)?;
> // ys.bboxes()
> ```

thanks~
