### ISSUE TITLE
Some questions about multithreading

### ISSUE THREAD

**Issue by mchenryXD** [jamjamjon/usls#21]
Can I load the model only once for multiple asynchronous image processing? Will using multithreading have any impact if possible?

**Comment by mchenryXD** [comment]
Actually, I want to develop upper computer software for machine vision. This is my first attempt to use Rust instead of C++, and I am currently testing its feasibility

**Comment by jamjamjon** [comment]
Sounds cool! You should carefully review the `ort` crate for more information! Similarly, you can use projects like `candle` and `burn` for model inference.

**Comment by mchenryXD** [comment]
They have some strict requirements for me, a beginner like Rust. Can I use your code if I only need to run the model at software startup and transfer images when the camera triggers photography

**Comment by mchenryXD** [comment]
thanks
