### ISSUE TITLE
ShapeError/IncompatibleShape,  at 0.0.5

### ISSUE THREAD

**Issue by Fred2754** [jamjamjon/usls#25]
## When I upgraded to 0.0.5, I found some error at runtime:

cargo run -r --example yolo -- --task detect --version v10 --model models\l1000_d_s.onnx --source assets\8104old.png

✅ ORT: 1.17.x | Opset: 13 | EP: Cpu(0) | Dtype: [Float32] | Parameters: 23.2 MiB
YOLO Task: Detect, Version: Some(V10)
✅ Dryrun x5
✅ Found images x1 (1 total)
Error: ShapeError/IncompatibleShape: incompatible shapes

## It looks like a problem of model, but the model runs well with usls 0.0.3 and yolov10
python .\predict.py --model l1000_d_s.onnx --source .\datasets\test\8104old.png

Loading l1000_d_s.onnx for ONNX Runtime inference...
image 1/1 R:\yolov10\datasets\test\8104old.png: 640x640 1 S6, 1 C6, 2 backs, 623.8ms
Speed: 3.0ms preprocess, 623.8ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)

Am I missing some important parameters in the new version?

**Comment by jamjamjon** [comment]
Can you show me the input and output shapes of your ONNX model? Or you can upload it here if you don't mind.

Does it match with this ?

![image](https://github.com/user-attachments/assets/771ab0ad-aa73-483e-9d9e-2376a7e61f74)

**Comment by Fred2754** [comment]
[l1000_1.zip](https://github.com/user-attachments/files/16347336/l1000_1.zip)
[l1000_2.zip](https://github.com/user-attachments/files/16347340/l1000_2.zip)
[l1000_3.zip](https://github.com/user-attachments/files/16347341/l1000_3.zip)

Pls rename:
l1000_1.zip => l1000.zip.001
l1000_2.zip => l1000.zip.002
l1000_3.zip => l1000.zip.002

Here's my export code:

from ultralytics import YOLOv10

model = YOLOv10('l1000.pt')

  model.export(
	  format="onnx",
      dynamic=True,
      simplify=True,
      opset=13
  )

**Comment by jamjamjon** [comment]
The code and model are running fine on my machine. The following result is running on the image `assets/bus.jpg`. 

```Shell

✅ ORT: 1.17.x | Opset: 13 | EP: Cpu(0) | Dtype: [Float32] | Parameters: 23.2 MiB
YOLO Task: Detect, Version: Some(V10)
✅ Dryrun x5
✅ Found images x1 (1 total)
✅ Annotated image saved to: runs/YOLO-Series/2024-07-23-19-21-25-062485917.png
[Y { BoundingBoxes: [Bbox { xyxy: [564.2526, 78.53694, 659.074, 263.76144], class_id: 53, name: Some("yellow"), confidence: 0.9853983 }, Bbox { xyxy: [221.43134, 8.105438, 330.42154, 238.58904], class_id: 53, name: Some("yellow"), confidence: 0.5972019 }, Bbox { xyxy: [-0.010833979, 0.25871515, 124.03327, 191.5599], class_id: 53, name: Some("yellow"), confidence: 0.25055158 }] }]

```
![2024-07-23-19-21-46-459954903](https://github.com/user-attachments/assets/38dd76bf-c1a9-42e7-8722-2b0e4910a5b1)

Do you mind providing an image for inference testing?

**Comment by jamjamjon** [comment]
Test on:
ONNXRuntime: 1.17.3
OS: Ubuntu 24.04 LTS
Rustc: 1.79.0 (129f3b996 2024-06-10)

**Comment by Fred2754** [comment]
Oh, my God, I tried to test it with the image(assets/bus.jpg), it worked...
Pls try this image, maybe it'll help you find something
[8104old.zip](https://github.com/user-attachments/files/16350609/8104old.zip)

**Comment by jamjamjon** [comment]
Ok, I will check that.
