### ISSUE TITLE
Got 'error LNK2038: Mismatch detected for"RuntimeLibrary''...' when work with fltk

### ISSUE THREAD

**Issue by Fred2754** [jamjamjon/usls#31]
cargo run

------------

use fltk::{app, prelude::*, window::Window};
use usls::Bbox;

fn main() {
    let _box = Bbox::from((0.0, 0.0, 0.0, 0.0));

    let app = app::App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.end();
    wind.show();
    app.run().unwrap();
}

**Comment by jamjamjon** [comment]
I haven't used the `fltk` library before. Are you sure you can run the demo you provided using `fltk` without using `usls`?

**Comment by Fred2754** [comment]
> This is probably a linking issue that seems to have occurred when you were compiling the `fltk` crate. It has nothing to do with the `usls` crate. I haven't used the `fltk` library before. Are you sure you can run the demo you provided using `fltk` without using `usls`?

Here are the test results in windows11:
1 fltk is work fine without usls, in debug or release mode
2 fltk & usls: runs well in release(cargo run --release), but have some compile error in debug(cargo run):

libfltk_sys-322ed3830f48030e.rlib(cfl_utils.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libesaxx_rs-f50c9dc542748ff1.rlib(2e40c9e35e9506f4-esaxx.o

Maybe the project need a toolchain file with /MT(d), but I have no idea about what to do.

**Comment by jamjamjon** [comment]
> > This is probably a linking issue that seems to have occurred when you were compiling the `fltk` crate. It has nothing to do with the `usls` crate. I haven't used the `fltk` library before. Are you sure you can run the demo you provided using `fltk` without using `usls`?
> 
> 
> 
> Here are the test results in windows11:
> 
> 1 fltk works fine without usls, in debug or release mode
> 
> 2 fltk & usls: runs well in release(cargo run --release), but have some compile error in debug(cargo run):
> 
> 
> 
> libfltk_sys-322ed3830f48030e.rlib(cfl_utils.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”(libesaxx_rs-f50c9dc542748ff1.rlib(2e40c9e35e9506f4-esaxx.o
> 
> 
> 
> Maybe the project need a toolchain file with /MT(d), but I have no idea about what to do.

Does 'usls' work fine in both Debug and Release mode?

**Comment by jamjamjon** [comment]
@Fred2754  You can refer to: https://github.com/pykeio/ort/issues/255

**Comment by Fred2754** [comment]
'usls' works fine in both mode.
You are right. It's about msvc, and it's a problem of 'esaxx_rs'(depended by tokenizers, which us in usls )

**Comment by Fred2754** [comment]
The 'esaxx_rs' library looks like it hasn't been maintained for a long time, so I had to force an override dependency to fix the error.

Here are my steps:
1 download the source code(https://github.com/narsil/esaxx-rs)
2 set "static_crt(false)" in the build.rs
3 add dependencies to the main project, looks like:
  esaxx-rs = { path = "../esaxx-rs" }
4 write a line of code, or the compiler will ignore useless ones. just:
  let _suffix = esaxx_rs::suffix("abracadabra").unwrap();

**Comment by jamjamjon** [comment]
> The 'esaxx_rs' library looks like it hasn't been maintained for a long time, so I had to force an override dependency to fix the error.
> 
> 
> 
> Here are my steps:
> 
> 1 download the source code(https://github.com/narsil/esaxx-rs)
> 
> 2 set "static_crt(false)" in the build.rs
> 
> 3 add dependencies to the main project, looks like:
> 
>   [patch.crates-io]
> 
> esaxx-rs = { path = "libs/esaxx-rs" }
> 
> 

Nice try！ Thanks for your solution.
