### ISSUE TITLE
usls default feature has contains `ort/half`, but load float16 model error

### ISSUE THREAD

**Issue by phial3** [jamjamjon/usls#40]
```text
Error: Load model from /Users/admin/code/models/v5/mix_0715.onnx failed:Type Error: Type parameter (T) of Optype (Concat) bound to different types (tensor(float) and tensor(float16) in node (Concat_498).
```

**Comment by jamjamjon** [comment]
It seems that this error is likely caused by the ONNX model. It incorrectly concatenated float and float16. Please ensure that both sides of the concatenation have matching data types.

Perhaps you should re-export the ONNX model or apply quantization uniformly to the entire ONNX model.
