### ISSUE TITLE
YOLO - Restrict detection classes

### ISSUE THREAD

**Issue by pplanel** [jamjamjon/usls#44]
Hi, thanks for this library, great work!
As the title says, how could I restrict the detections classes?
And the options/parameters prefixed with `i`1-275 are related to what?

Thanks!

**Comment by jamjamjon** [comment]
You can now use `Options::new().exclude_classes()` to filter out some classes, and use `Options::new().retain_classes()` to specify detecting only the provided classes in in version `v0.0.18`.

### Refer to the YOLO demo 
https://github.com/jamjamjon/usls/blob/1d596383ded00b7cc11a6955c30b33b8751bf86e/examples/yolo/main.rs#L163-L164

**Comment by pplanel** [comment]
Thanks!
