### ISSUE TITLE
Win10 platform debugging error: failed to run custom build command for ffmpeg-sys next v7.1.0`

### ISSUE THREAD

**Issue by mingtianquan** [jamjamjon/usls#48]

**Comment by jamjamjon** [comment]
You can refer to https://github.com/zmwangx/rust-ffmpeg/issues

**Comment by mingtianquan** [comment]
109/10000
实时翻译
现在已经编译好了，可以运行示例代码，cargo run-r--example-yolo可以正常运行。但我自己加载了这个库，在使用示例代码时遇到了错误。错误：❌ TensorRT初始化失败

划译
Now that it has been compiled, the example code can be run, and cargo run - r -- example yolo can run normally
But I loaded this library myself and encountered an error using the example code. Error: ❌ TensorRT initialization failed
![Uploading QQ截图20241028175403.png…]()

**Comment by mingtianquan** [comment]
C:/Users/hai/.cargo/bin/cargo.exe run --color=always --package yolov8 --bin yolov8
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running `target\debug\yolov8.exe`
Error: ❌ TensorRT initialization failed

Stack backtrace:
   0: std::backtrace_rs::backtrace::dbghelp64::trace
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2: std::backtrace::Backtrace::create
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\backtrace.rs:331
   3: std::backtrace::Backtrace::capture
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\backtrace.rs:296
   4: anyhow::Error::msg<alloc::string::String>
             at C:\Users\hai\.cargo\registry\src\index.crates.io-6f17d22bba15001f\anyhow-1.0.91\src\backtrace.rs:27
   5: anyhow::__private::format_err
             at C:\Users\hai\.cargo\registry\src\index.crates.io-6f17d22bba15001f\anyhow-1.0.91\src\lib.rs:694
   6: usls::core::ort_engine::OrtEngine::build_trt
             at C:\Users\hai\.cargo\registry\src\index.crates.io-6f17d22bba15001f\usls-0.0.19\src\core\ort_engine.rs:204
   7: usls::core::ort_engine::OrtEngine::new
             at C:\Users\hai\.cargo\registry\src\index.crates.io-6f17d22bba15001f\usls-0.0.19\src\core\ort_engine.rs:95
   8: usls::models::yolo::impl$0::new
             at C:\Users\hai\.cargo\registry\src\index.crates.io-6f17d22bba15001f\usls-0.0.19\src\models\yolo.rs:40
   9: yolov8::main
             at .\src\main.rs:14
  10: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),tuple$<> >
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\core\src\ops\function.rs:250
  11: std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,anyhow::Error> > (*)(),enum2$<core::result::Result<tuple$<>,anyhow::Error> > >
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\std\src\sys_common\backtrace.rs:155
  12: std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,anyhow::Error> > >
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\std\src\rt.rs:159
  13: std::rt::lang_start_internal
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\rt.rs:141
  14: std::rt::lang_start<enum2$<core::result::Result<tuple$<>,anyhow::Error> > >
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\std\src\rt.rs:158
  15: main
  16: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  17: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\yolov8.exe` (exit code: 1)

进程已结束，退出代码为 1

**Comment by mingtianquan** [comment]
Can't the model trained with yolov8n.pt be used?

**Comment by mingtianquan** [comment]
Converted to YOLO export model=runs/detect/train4/weights/best. pt format=onnx simplify dynamic
Onnx format

**Comment by jamjamjon** [comment]
Sure! The official YOLOv8 model should be problem-free. Would you mind sharing your model loading code?

**Comment by mingtianquan** [comment]
use usls::{models::YOLO, Annotator, DataLoader, Nms, Options, Vision, YOLOTask, YOLOVersion, Viewer};

fn main() -> anyhow::Result<()> {
    // Build model with Options
    let options = Options::new()
        .with_trt(0)
        .with_model("C:/Users/hai/Desktop/dd/yolov8/src/best.onnx")?
        .with_yolo_version(YOLOVersion::V8) // YOLOVersion: V5, V6, V7, V8, V9, V10, RTDETR
        .with_yolo_task(YOLOTask::Detect) // YOLOTask: Classify, Detect, Pose, Segment, Obb
        .with_ixx(0, 0, (1, 2, 4).into())
        .with_ixx(0, 2, (0, 640, 640).into())
        .with_ixx(0, 3, (0, 640, 640).into())
        .with_confs(&[0.2]);
    let mut model = YOLO::new(options)?;

    // Build DataLoader to load image(s), video, stream
    let dl = DataLoader::new(
        "C:/Users/hai/Desktop/dd/yolov8/src/3_jpg.rf.8fb6bd56ea94bb8031ea55ab2265f0b4.jpg", // local image
        // "images/bus.jpg",  // remote image
        // "../images-folder",  // local images (from folder)
        // "../demo.mp4",  // local video
        // "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",  // online video
        // "rtsp://admin:kkasd1234@192.168.2.217:554/h264/ch1/",  // stream
    )?
        .with_batch(2)  // iterate with batch_size = 2
        .build()?;

    // Build annotator
    let annotator = Annotator::new()
        .with_bboxes_thickness(4)
        .with_saveout("YOLO-DataLoader");

    // Build viewer
    let mut viewer = Viewer::new().with_delay(10).with_scale(1.).resizable(true);

    // Run and annotate results
    for (xs, _) in dl {
        let ys = model.forward(&xs, false)?;
        // annotator.annotate(&xs, &ys);
        let images_plotted = annotator.plot(&xs, &ys, false)?;

        // show image
        viewer.imshow(&images_plotted)?;

        // check out window and key event
        if !viewer.is_open() || viewer.is_key_pressed(usls::Key::Escape) {
            break;
        }

        // write video
        viewer.write_batch(&images_plotted)?;

        // Retrieve inference results
        for y in ys {
            // bboxes
            if let Some(bboxes) = y.bboxes() {
                for bbox in bboxes {
                    println!(
                        "Bbox: {}, {}, {}, {}, {}, {}",
                        bbox.xmin(),
                        bbox.ymin(),
                        bbox.xmax(),
                        bbox.ymax(),
                        bbox.confidence(),
                        bbox.id(),
                    );
                }
            }
        }
    }

    // finish video write
    viewer.finish_write()?;

    Ok(())
}

**Comment by jamjamjon** [comment]
Do not set min height and width to 0

Modify them
```
.with_ixx(0, 2, (0, 640, 640).into())
.with_ixx(0, 3, (0, 640, 640).into())
```

to
```

.with_ixx(0, 2, (320, 640, 640).into())
.with_ixx(0, 3, (320, 640, 640).into())

```

**Comment by mingtianquan** [comment]
但是还是运行不起来一样的报错呀，
Error: ❌ TensorRT initialization failed
哎折腾一天了
63/10000
实时翻译
划译
But it still doesn't run with the same error message,
Error:  ❌ TensorRT initialization failed
Hey, it's been a whole day of tinkering

**Comment by jamjamjon** [comment]
tensorrt version？

**Comment by mingtianquan** [comment]
Tensor version is not installed, but it can be run by running the YOLO example in the source code directory. Do we still need to install Tensor?

**Comment by jamjamjon** [comment]
Clone the `usls` project and run the following command. If it fails, it’s likely an issue with your TensorRT installation. Please check the version and environment variables. 

```
cargo run -r --example yolo -- --task detect --ver v8 --scale n --trt

```

**Comment by mingtianquan** [comment]
C:\Users\hai\Desktop\dd\usls-main>cargo run -r --example yolo -- --task detect --ver v8 --scale n --trt
   Compiling ort-sys v2.0.0-rc.8
   Compiling usls v0.0.19 (C:\Users\hai\Desktop\dd\usls-main)
   Compiling ort v2.0.0-rc.5
    Finished `release` profile [optimized] target(s) in 47.04s
     Running `target\release\examples\yolo.exe --task detect --ver v8 --scale n --trt`
Error: ❌ TensorRT initialization failed
error: process didn't exit successfully: `target\release\examples\yolo.exe --task detect --ver v8 --scale n --trt` (exit code: 1)

C:\Users\hai\Desktop\dd\usls-main>

**Comment by mingtianquan** [comment]
Then why can running cargo run-r in the cloned directory? For example, YOLO can recognize and generate images under the generated runs normally and annotate them

**Comment by jamjamjon** [comment]
> Then why can running cargo run-r in the cloned directory? For example, YOLO can recognize and generate images under the generated runs normally and annotate them

Can you run the yolo demo without TensorRT installed but actually using tensorrt execute provider?  I guess you are runting with CPU or Cuda.

**Comment by mingtianquan** [comment]
That should be in that version of Tensor
Available Versions
TensorRT 10
TensorRT 8
TensorRT 7
TensorRT 6
TensorRT 5
TensorRT 4
TensorRT 3
TensorRT 2
TensorRT 1

**Comment by jamjamjon** [comment]
TensorRT 10

**Comment by mingtianquan** [comment]
C:\Users\hai>dir %TRT_LIBPATH%
 驱动器 D 中的卷是 Sanxin
 卷的序列号是 6359-04A1

 D:\TensorRT-10.0.1.6\lib 的目录

2024/04/17  02:08    <DIR>          .
2024/04/17  02:08    <DIR>          ..
2024/04/17  02:07     1,342,175,784 nvinfer_builder_resource_10.dll
2024/04/17  02:07        29,492,776 nvinfer_lean_10.dll
2024/04/17  02:07           606,760 nvinfer_dispatch_10.dll
2024/04/17  02:06             5,684 nvinfer_10.lib
2024/04/17  02:06             2,524 nvonnxparser_10.lib
2024/04/17  02:07         2,631,208 nvonnxparser_10.dll
2024/04/17  02:06             2,842 nvinfer_vc_plugin_10.lib
2024/04/17  02:08       206,784,040 nvinfer_10.dll
2024/04/17  02:06             2,784 nvinfer_plugin_10.lib
2024/04/17  02:06             5,098 nvinfer_lean_10.lib
2024/04/17  02:08        30,397,480 nvinfer_plugin_10.dll
2024/04/17  02:08        30,397,480 nvinfer_vc_plugin_10.dll
2024/04/17  02:06             4,362 nvinfer_dispatch_10.lib
              13 个文件  1,642,508,822 字节
               2 个目录 265,616,883,712 可用字节

C:\Users\hai>

**Comment by mingtianquan** [comment]
After downloading, the system environment variable TRT_LIBPATH=D: \ TensorRT-10.0.1.6 \ lib was set
Path = D:\TensorRT-10.0.1.6\lib
