### ISSUE TITLE
TensorRT initialization failed

### ISSUE THREAD

**Issue by chad-green** [jamjamjon/usls#49]
I have onnxruntime with GPU support setup on my Jetson Orin NX. I can see that the TensorrtExecutionProvider is available in Python:
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime as ort
>>> print(ort.get_available_providers())
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

And I can run your yolo example with --cuda, but when I run it with --trt, I get the below. I have made sure that I exported the ORT_DYLIB_PATH variable and it finds it just fine. 

cargo run -r --example yolo -- --task detect --ver v5 --scale n --trt
    Finished `release` profile [optimized] target(s) in 0.30s
    Running `target/release/examples/yolo --task detect --ver v5 --scale n --trt`
Error: ❌ TensorRT initialization failed

**Comment by jamjamjon** [comment]
I haven't tested it on a Jetson device. You can first check if the TensorRT version is higher than 10.x. If the version is appropriate, you may need to compile ONNXRuntime from source.

You can refer to [this](https://ort.pyke.io/setup/platforms)

**Comment by chad-green** [comment]
Thank you for the response. I got it to work. There are pre-built onnxruntime-gpu binaries [here](https://elinux.org/Jetson_Zoo#ONNX_Runtime)

The problem was missing libcudnn libraries. I found it by adding a little more debug in ort_engine.rs:

-        if trt.is_available()? && trt.register(builder).is_ok() {
-            tracing::info!("🐢 Initial model serialization with TensorRT may require a wait...\n");
-            Ok(())
-        } else {
-            anyhow::bail!("{CROSS_MARK} TensorRT initialization failed")
+        
+        tracing::info!("Checking if TensorRT is av
ailable...");
+        if !trt.is_available()? {
+            tracing::error!("TensorRT is not available.");
+            return Err(anyhow::anyhow!("TensorRT is not available"));
+        }
+
+        tracing::info!("Registering TensorRT execution provider...");
+        match trt.register(builder) {
+            Ok(_) => {
+                tracing::info!("🐢 Initial model s
erialization with TensorRT may require a wait...\n");
+                Ok(())
+            }
+            Err(e) => {
+                tracing::error!("Failed to register TensorRT execution provider: {:?}", e);
+                Err(anyhow::anyhow!("Failed to register TensorRT execution provider: {:?}", e))
+            }

It showed me that libcudnn.so.8 wasn't being found. As always with tensorrt, getting all the versions to be compatible is a challenge. I started with l4t-tensorrt from nvidia: FROM nvcr.io/nvidia/l4t-tensorrt:r8.6.2-devel
then installed the pre-built onnxruntime-gpu mentioned earlier and exported the ORT_DYLIB_PATH to match. After that, the trt optimization ran correctly.

**Comment by jamjamjon** [comment]
Glad to hear that you solved the problem.
