### ISSUE TITLE
使用示例中的db模型代码运行了几张图片，发现没有示例给出的图片效果好

### ISSUE THREAD

**Issue by jiabochao** [jamjamjon/usls#51]
您好，我直接使用db模型示例代码，在网上截了几张图进行处理，发现不管是英文还是中文，都没法完全覆盖文字，但是示例中的两张图片，效果却很好，这是什么原因呢？

![image](https://github.com/user-attachments/assets/bdcad4e7-6fc3-4c80-ad8e-30ebd4c0414a)

![image](https://github.com/user-attachments/assets/5c248a73-e8df-4dd4-b1fd-b14de26b517d)

边界没有示例图片的好，

![image](https://github.com/user-attachments/assets/967a731f-e092-44fb-a932-ec74515ee917)

![image](https://github.com/user-attachments/assets/d8023135-2a67-4d58-98d4-911adeb6b333)

原始图片在这里：

![image](https://github.com/user-attachments/assets/5e2a4865-2076-4d5e-aef6-b262c944bc01)

![image](https://github.com/user-attachments/assets/4b219ab3-507e-4304-9162-099f5660607e)

**Comment by jamjamjon** [comment]
你好，可能的原因是输入图片分辨率过大导致的。本项目`DB`算法实现中前后处理和`PaddleOCR`官方不同：
1、前处理使用了`letterbox`的方式统一缩放到了输入分辨率，官方代码似乎是长或短边缩放到960（这个我记不清楚了）；
2、后处理中的`unclip`操作的对象是`polygon`而不是官方代码中默认的`box(quad)`。你可以先调整一下输入分辨率来看看结果。如果结果仍然不正确的话，你可以参考代码中的后处理来修改成基于`box(quad)`： https://github.com/jamjamjon/usls/blob/57db14ce5d04eebd51708c81b7850b078727aadd/src/models/db.rs#L128-L134

我暂时没有机器来测试你提供的图片，我会在稍后进行测试。

**Comment by jamjamjon** [comment]
Try this:
```shell
let options = Options::default()
        .with_ixx(0, 0, (1, 4, 8).into())
        .with_ixx(0, 2, 1536.into())
        .with_ixx(0, 3, 1536.into())
        .with_model("db/ppocr-v4-db-dyn.onnx")?;
```

![2024-11-26-19-30-05-761043275](https://github.com/user-attachments/assets/90485958-d230-4529-b222-02bdcc637ad8)
![2024-11-26-19-30-05-780857830](https://github.com/user-attachments/assets/f6cc091d-c413-4e71-b763-f0d242de226f)

**Comment by jiabochao** [comment]
> Try this:
> 
> ```shell
> let options = Options::default()
>         .with_ixx(0, 0, (1, 4, 8).into())
>         .with_ixx(0, 2, 1536.into())
>         .with_ixx(0, 3, 1536.into())
>         .with_model("db/ppocr-v4-db-dyn.onnx")?;
> ```
@jamjamjon 非常感谢您的及时回复，我尝试了此参数配置，现在识别效果非常好。我对这些参数的含义并不是太了解，想请教一下这些参数需要根据不同的图片规格进行调整吗，还是当前配置已经可以适用大多数的场景。

**Comment by jamjamjon** [comment]
如果输入图片分辨率比较大的话（如上面两张图片分辨率都是2k*1K多），建议模型的输入分辨率也相应提高，如1280，1536；如果小于等于1280P的输入图片的话，可以使用960。需要注意的是：模型输入的分辨率提高会导致推理速度变慢。在使用场景不变的情况下，选择调试合适的模型输入分辨率即可。

后续有时间我会对齐后处理，使用更简单的Box unclip来进行处理，处理速度也会加快。

**Comment by jiabochao** [comment]
> 如果输入图片分辨率比较大的话（如上面两张图片分辨率都是2k*1K多），建议模型的输入分辨率也相应提高，如1280，1536；如果小于等于1280P的输入图片的话，可以使用960。需要注意的是：模型输入的分辨率提高会导致推理速度变慢。在使用场景不变的情况下，选择调试合适的模型输入分辨率即可。
> 
> 后续有时间我会对齐后处理，使用更简单的Box unclip来进行处理，处理速度也会加快。

@jamjamjon 感谢解答，非常好的项目，期待进一步的提升。问题已解决，我就将这个issue关闭了。
